server:
  port: 9901

rsa:
  # \u516C\u94A5\uFF0C\u9700\u670D\u52A1\u7AEF\u63D0\u4F9B
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCpibahn7J+E65IoObnW56D6rxx6I4Zvs6s+uYIZHAd6Ar2yQk/xXaVoMjTTZkcyW66Edc9Oo8J2sFL4SVMyQmF3fj/zz9bUD69HKck6Q/ERS4790eLDr9HaZrL/svmZihISHk1mo9hegHrU2LovfBpwVZ/ODU4DN9cyARyLWlaXwIDAQAB